export const usaStates: { [stateName: string]: string } = {
  Alabama: "AL",
  Alaska: "AK",
  Arizona: "AZ",
  Arkansas: "AR",
  California: "CA",
  Colorado: "CO",
  Connecticut: "CT",
  Delaware: "DE",
  Florida: "FL",
  Georgia: "GA",
  Hawaii: "HI",
  Idaho: "ID",
  Illinois: "IL",
  Indiana: "IN",
  Iowa: "IA",
  Kansas: "KS",
  Kentucky: "KY",
  Louisiana: "LA",
  Maine: "ME",
  Maryland: "MD",
  Massachusetts: "MA",
  Michigan: "MI",
  Minnesota: "MN",
  Mississippi: "MS",
  Missouri: "MO",
  Montana: "MT",
  Nebraska: "NE",
  Nevada: "NV",
  New_Hampshire: "NH",
  New_Jersey: "NJ",
  New_Mexico: "NM",
  New_York: "NY",
  North_Carolina: "NC",
  North_Dakota: "ND",
  Ohio: "OH",
  Oklahoma: "OK",
  Oregon: "OR",
  Pennsylvania: "PA",
  Rhode_Island: "RI",
  South_Carolina: "SC",
  South_Dakota: "SD",
  Tennessee: "TN",
  Texas: "TX",
  Utah: "UT",
  Vermont: "VT",
  Virginia: "VA",
  Washington: "WA",
  West_Virginia: "WV",
  Wisconsin: "WI",
  Wyoming: "WY",
};

export const propertyTypes = {
  "":"Immobilienart",
  "single_family": "Einfamilienhaus",
  "multi_family": "Mehrfamilienhaus",
  "mobile": "Mobilheim",
  "farm": "Bauernhof",
  "land": "Grundstück",
};

export const propertyTypesResult={
  "":"Immobilienart",
  "single_family": "Einfamilienhaus",
  "multi_family": "Mehrfamilienhaus",
  "mobile": "Mobilheim",
  "farm": "Bauernhof",
  "land": "Grundstück",
  "mls":"MLS",
  "office":"Office",
  "condos":"Condos",
  "townhomes":"Reihenhäuser"
}

export const imageFiles = [
  "img.jpg",
  "img (1).jpg",
  "img (2).jpg",
  "img (3).jpg",
  "img (4).jpg",
  "img (5).jpg",
  "img (6).jpg",
  "img (7).jpg",
  "img (8).jpg",
  "img (9).jpg",
  "img (10).jpg",
  "img (11).jpg",
  "img (12).jpg",
  "img (13).jpg",
  "img (14).jpg",
  "img (15).jpg",
  "img (16).jpg",
  "img (17).jpg",
  "img (18).jpg",
  "img (19).jpg",
  "img (20).jpg",
  "img (21).jpg",
  "img (22).jpg",
  "img (23).jpg",
  "img (24).jpg",
  "img (25).jpg",
  "img (26).jpg",
];


export const footerLinks = [
  {
    title: "About",
    links: [
      { title: "How it works", url: "/", imageUrl:"" },
      { title: "Featured", url: "/", imageUrl:""  },
      { title: "Partnership", url: "/" , imageUrl:"" },
      { title: "Bussiness Relation", url: "/", imageUrl:""  },
    ],
  },
  {
    title: "Company",
    links: [
      { title: "Events", url: "/", imageUrl:"" },
      { title: "Blog", url: "/" , imageUrl:"" },
      { title: "Podcast", url: "/", imageUrl:""  },
      { title: "Invite a friend", url: "/", imageUrl:""  },
    ],
  },
  {
    title: "Socials",
    links: [
      { title: "Discord", url: "https://wwww.discord.com" ,imageUrl:"discord-logo.png" },
      { title: "Instagram", url: "https://wwww.Instagram.com" ,imageUrl:"instagram-logo.png" },
      { title: "Twitter", url: "https://wwww.Twitter.com"  ,imageUrl:"twitter-logo.png"},
      { title: "Facebook", url: "https://wwww.Facebook.com"  ,imageUrl:"facebook-logo.png"},
    ],
  },
];

export const sortBy ={
  "relevant":"relevanteste",
  "newest":"neueste",
  "lowest_price":"teuerste",
  "highest_price":"billigste",
  "largest_sqft":"größte",
}


